# This is the config for the spigot side.
# You can find more settings in the config of bungee.


# Should we send queue requests from commands in batches?
# Enable this if you have issues with players sometimes not executing commands correctly
# Note though that it could delay queue commands by up to 1 second!
send-queue-commands-in-batches: false

# Should we take over the server MOTD to tell the proxy if the server is whitelisted?
# If you disable this, ajQueue will not be able to tell if the server is whitelisted!
take-over-motd-for-whitelist: true

# Should we check if the proxy responds to plugin messages?
# For some reason this seems to fail for some people,
#  so disable this if ajqueue says its not installed on the proxy when it actually is
check-proxy-response: true


# Should we register /queue (and its aliases) and /leavequeue on the backend?
# That way if those commands are run on a gui, npc, etc, we can automatically forward them to the proxy
#  Default: true
enable-commands: true

# Should we register /server as an alias for /queue?
# Note this only applies to the backend server (e.g. if /server is run on npcs/guis/etc.)
# If you want to replace the /server command on the proxy, follow this guide: https://wiki.ajg0702.us/ajQueue/setup/replacing-server-command
#  Default: true
enable-server-alias: true

# Should we enable /spigotqueue alias for /queue?
# This is mainly for debugging, which is why its disabled by default
#  Default: false
enable-spigotqueue-alias: false



# Dont touch this
config-version: 4